os: 
    - linux
    - osx
osx_image: xcode11.3
dist: trusty
language: cpp
addons:
  apt:
    packages:
      - libpulse-dev 
      - libgtk-3-dev
      - freeglut3 
      - freeglut3-dev
      - libhamlib-dev
script: 
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install hamlib; fi
    - bash travis-ci/build_liquiddsp.sh
    - bash travis-ci/build_soapysdr.sh
    - bash travis-ci/build_wxwidgets.sh
    - bash travis-ci/build_cubicsdr.sh
cache:
    directories:
     - $HOME/build/wxWidgets/staticlib
